# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21
parchment_mappings_version=2024.11.10
minecraft_version=1.21.1
fabric_version=0.116.12+1.21.1
loader_version=0.19.2

# Mod Properties
mod_version = 0.1.0
maven_group = com.github.salandora
mod_id = sophisticatedfabriclib
github_package_url=https://maven.pkg.github.com/Salandora/SophisticatedFabricLib

#publish
curseforge_id=1521863
modrinth_project_id=TvkDVFF5
# Release types: STABLE, BETA, ALPHA
release_type=BETA
curseforge_minecraft_versions=1.21.1
modrinth_minecraft_versions=1.21.1

# Dependencies
energy_version = 4.1.0