name: Release
on:
  workflow_dispatch: # Manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/cache@v5
        with:
          path: "**/.gradle/loom-cache"
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}"
          restore-keys: "${{ runner.os }}-gradle-"
      - uses: gradle/actions/wrapper-validation@v5
      - run: chmod +x ./gradlew
      - run: ./gradlew build --stacktrace --no-configuration-cache
      - name: Publish
        run: ./gradlew publish publishMods -x check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'com.github.salandora.sophisticatedfabriclib'
          package-type: 'maven'
          min-versions-to-keep: 10
